Sales.WebUI/Controllers/AccountController.cs
using Sales.Domain.Entities;
using Sales.WebUI.Infrastructure.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;
        public AccountController(IAuthProvider auth)
        {
            authProvider = auth;
        }
        public ViewResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(user.Name, user.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

Sales.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sales.Domain.Abstract;
using Sales.Domain.Entities;
using Sales.WebUI.Infrastructure.Abstract;

namespace Sales.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IProductRepository repository;
        private IAuthProvider authProvider;

        public HomeController(IProductRepository productRepository, IAuthProvider auth)
        {
            this.repository = productRepository;
            this.authProvider = auth;
        }

        public ActionResult Index(string selectedProduct = null)
        {
            Product product = (selectedProduct != null) ?
                repository.Products.FirstOrDefault(x => x.Name == selectedProduct) :
                repository.Products.FirstOrDefault();
            ViewBag.SelectedProduct = product.Name;
            return View(product);
        }


        public PartialViewResult Upload()
        {
           return PartialView();
        }

        public PartialViewResult OrderProcess(string selectedProduct)
        {
            Product product = (selectedProduct != null) ?
                repository.Products.FirstOrDefault(x => x.Name == selectedProduct) :
                repository.Products.FirstOrDefault();
            return PartialView(product);
        }

        public PartialViewResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Login(User user, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(user.Name, user.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }


        

    }
}

Sales.WebUI/Controllers/NavController.cs
using Sales.Domain.Abstract;
using Sales.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sales.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository rep)
        {
            repository = rep;
        }

        public PartialViewResult Menu(string selectedProduct = null)
        {
            ViewBag.SelectedProduct = selectedProduct;

            IEnumerable<string> productNames = repository.Products.Select(x => x.Name);
            return PartialView(productNames);
        }
    }
}

Sales.WebUI/Views/Home/Index.cshtml
@using Sales.Domain.Entities
@model Product

@{
    ViewBag.Title = "Index";
}

<style>
    #sales { background-color: rgb(255, 240, 240)}
</style>

<h3>@Model.Name</h3>

Umbraco content for product: @Model.Name

<div id="sales" class="col-xs-12 well well-sm">
    @Html.Action("OrderProcess", "Home", new { selectedProduct = ViewBag.SelectedProduct })
</div>

Sales.WebUI/Views/Home/OrderProcess.cshtml
order process functionaliry

Sales.WebUI/Views/Home/Product.cshtml
Product

Sales.WebUI/Views/Home/Upload.cshtml
Upload an image

Sales.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>


<div class="btn-group" role="group" aria-label="...">

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new { controller = "Home", action = "Index", selectedProduct = link, page = 1 },
        new {
            @class = "btn btn-default"
        })
    }

</div>

Sales.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">AUTHENTIC</a>
    </div>

    <div class="row panel">

        <div id="products" class="col-xs-12 well">
            @Html.Action("Menu", "Nav")
        </div>
    
        <div class="col-xs-12 well">
            @RenderBody()
        </div>
    </div>
</body>
</html>